services:
  proxy:
    image: iam-service-image
    container_name: iam-service-container
    build:
      context: ..
    ports:
      - "8080:8080"
    networks:
      - pi


networks:
  pi:
    driver: bridge