server:
  port: 8081

spring:

  data:
    web:
      pageable:
        default-page-size: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ACCOUNTS_DATABASE_HOST:localhost}:${ACCOUNTS_DATABASE_PORT:3306}/${ACCOUNTS_DATABASE_NAME:accounts_database}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${ACCOUNTS_DATABASE_USER:root}
    password: ${ACCOUNTS_DATABASE_PASSWORD:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

iamService:
  baseUrl: ${IAM_BASE_URL:http://localhost:8080}
