spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${IAM_DATABASE_HOST:localhost}:${IAM_DATABASE_PORT:3306}/${IAM_DATABASE_NAME:iam_database}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${IAM_DATABASE_USER:root}
    password: ${IAM_DATABASE_PASSWORD:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

email-service:
  host: ${EMAIL_HOST:""}
  port: ${EMAIL_PORT:""}
  ssl: ${EMAIL_SSL:""}
  tls: ${EMAIL_TLS:""}
  user: ${EMAIL_USER:""}
  password: ${EMAIL_PASSWORD:""}

api:
  baseUrl: ${IAM_BASE_URL:http://localhost:8080}

accountService:
  baseUrl: ${ACCOUNTS_BASE_URL:http://localhost:8081}
